#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path


def read_obj(path: Path) -> tuple[list[str], list[list[float]]]:
    lines = path.read_text(encoding="utf-8", errors="replace").splitlines()
    vertices: list[list[float]] = []
    for line in lines:
        if line.startswith("v "):
            parts = line.split()
            if len(parts) >= 4:
                vertices.append([float(parts[1]), float(parts[2]), float(parts[3])])
    if not vertices:
        raise RuntimeError(f"No vertices found in {path}")
    return lines, vertices


def apply_target(vertices: list[list[float]], target_path: Path, weight: float) -> int:
    changed = 0
    with target_path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw in handle:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 4:
                continue
            index = int(parts[0])
            if not 0 <= index < len(vertices):
                raise IndexError(f"Target index {index} outside 0..{len(vertices) - 1}")
            vertices[index][0] += float(parts[1]) * weight
            vertices[index][1] += float(parts[2]) * weight
            vertices[index][2] += float(parts[3]) * weight
            changed += 1
    return changed


def face_vertex_index(token: str, vertex_count: int) -> int:
    raw = int(token.split("/", 1)[0])
    if raw == 0:
        raise ValueError("OBJ vertex index 0 is invalid")
    return raw - 1 if raw > 0 else vertex_count + raw


def replace_face_vertex_index(token: str, new_one_based: int) -> str:
    fields = token.split("/")
    fields[0] = str(new_one_based)
    return "/".join(fields)


def collect_face_stats(
    lines: list[str], vertex_count: int, keep_groups: set[str] | None
) -> tuple[set[int], set[int], Counter[str]]:
    group = "__ungrouped__"
    kept_line_indexes: set[int] = set()
    used_vertices: set[int] = set()
    group_face_counts: Counter[str] = Counter()

    for line_index, line in enumerate(lines):
        if line.startswith("g "):
            group = line[2:].strip() or "__ungrouped__"
        elif line.startswith("f "):
            group_face_counts[group] += 1
            if keep_groups is None or group in keep_groups:
                kept_line_indexes.add(line_index)
                for token in line.split()[1:]:
                    index = face_vertex_index(token, vertex_count)
                    if not 0 <= index < vertex_count:
                        raise IndexError(f"Face index {index} outside 0..{vertex_count - 1}")
                    used_vertices.add(index)

    if not kept_line_indexes:
        selected = "all groups" if keep_groups is None else ", ".join(sorted(keep_groups))
        raise RuntimeError(f"No OBJ faces selected for {selected}")
    return kept_line_indexes, used_vertices, group_face_counts


def write_filtered_obj(
    lines: list[str],
    vertices: list[list[float]],
    output: Path,
    keep_groups: set[str] | None,
) -> dict[str, object]:
    kept_face_lines, used_vertices, group_face_counts = collect_face_stats(
        lines, len(vertices), keep_groups
    )
    ordered_used = sorted(used_vertices)
    remap = {old: new + 1 for new, old in enumerate(ordered_used)}
    rendered: list[str] = [
        "# AINA clean MakeHuman baseline",
        "# Generated by tools/makehuman_target_obj.py",
    ]
    vertex_cursor = 0
    current_group = "__ungrouped__"
    emitted_group: str | None = None

    for line_index, line in enumerate(lines):
        if line.startswith("v "):
            if vertex_cursor in remap:
                x, y, z = vertices[vertex_cursor]
                rendered.append(f"v {x:.9f} {y:.9f} {z:.9f}")
            vertex_cursor += 1
            continue
        if line.startswith("g "):
            current_group = line[2:].strip() or "__ungrouped__"
            continue
        if line.startswith("f "):
            if line_index not in kept_face_lines:
                continue
            if current_group != emitted_group:
                rendered.append(f"g {current_group}")
                emitted_group = current_group
            tokens = []
            for token in line.split()[1:]:
                old_index = face_vertex_index(token, len(vertices))
                tokens.append(replace_face_vertex_index(token, remap[old_index]))
            rendered.append("f " + " ".join(tokens))
            continue
        if line.startswith("o "):
            rendered.append("o AINA_MAKEHUMAN_CLEAN_BASE")
            continue
        rendered.append(line)

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(rendered) + "\n", encoding="utf-8")
    selected_counts = {
        group: count
        for group, count in sorted(group_face_counts.items())
        if keep_groups is None or group in keep_groups
    }
    return {
        "input_group_face_counts": dict(sorted(group_face_counts.items())),
        "selected_group_face_counts": selected_counts,
        "output_vertex_count": len(ordered_used),
        "output_face_count": len(kept_face_lines),
        "used_vertex_indexes": ordered_used,
    }


def bounds(vertices: list[list[float]]) -> dict[str, object]:
    axes = list(zip(*vertices))
    minimum = [min(axis) for axis in axes]
    maximum = [max(axis) for axis in axes]
    span = [high - low for low, high in zip(minimum, maximum)]
    largest_axis = max(range(3), key=lambda index: span[index])
    return {
        "min": minimum,
        "max": maximum,
        "span": span,
        "largest_axis": "XYZ"[largest_axis],
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--base", required=True, type=Path)
    parser.add_argument("--target", action="append", default=[], help="PATH:WEIGHT")
    parser.add_argument(
        "--keep-group",
        action="append",
        default=[],
        help="OBJ group to keep. Repeat for body/eyes/teeth/lashes.",
    )
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--report", required=True, type=Path)
    args = parser.parse_args()

    lines, vertices = read_obj(args.base)
    original = [row[:] for row in vertices]
    applied: list[dict[str, object]] = []
    for item in args.target:
        target_text, weight_text = item.rsplit(":", 1)
        target = Path(target_text)
        weight = float(weight_text)
        changed = apply_target(vertices, target, weight)
        applied.append({"path": str(target), "weight": weight, "changed_vertices": changed})

    keep_groups = set(args.keep_group) if args.keep_group else None
    output_stats = write_filtered_obj(lines, vertices, args.output, keep_groups)
    used_indexes = output_stats.pop("used_vertex_indexes")
    selected_vertices = [vertices[index] for index in used_indexes]
    max_delta = max(
        (
            (vertices[index][0] - original[index][0]) ** 2
            + (vertices[index][1] - original[index][1]) ** 2
            + (vertices[index][2] - original[index][2]) ** 2
        )
        ** 0.5
        for index in range(len(vertices))
    )
    report = {
        "base": str(args.base),
        "output": str(args.output),
        "input_vertex_count": len(vertices),
        "input_face_count": sum(1 for line in lines if line.startswith("f ")),
        "keep_groups": sorted(keep_groups) if keep_groups else "ALL",
        "base_bounds": bounds(original),
        "output_bounds": bounds(selected_vertices),
        "targets": applied,
        "max_vertex_delta": max_delta,
        "license_basis": "MakeHuman default basemesh and targets are CC0 per LICENSE.ASSETS.md",
        **output_stats,
    }
    args.report.parent.mkdir(parents=True, exist_ok=True)
    args.report.write_text(json.dumps(report, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
